server:
  port: 8088
spring:
  datasource:
    url: jdbc:h2:mem:mydb    #mem   创建一个名叫mydb的内存数据库，应用重启就没了
#    url: jdbc:h2:~/mydb    #~   在系统的home目录下创建一个名叫mydb的持久数据库
    driver-class-name: org.h2.Driver
    username: admin   #账号密码自己配置
    password: abc123
    schema: classpath:db/schema-h2.sql   # 启动应用时读取resources/db/schema-h2.sql 自动建表
    data: classpath:db/data-h2.sql      # 启动应用时读取resources/db/data-h2.sql 自动建表自动插数据

  h2:   #开启web控制台 访问地址  http://localhost:应用端口/h2-database
    console:
      enabled: true   #Whether to enable the console 是否启用控制台
      path: /h2-database   #Path at which the console is available.控制台可用路径
      settings:
        web-allow-others: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
